### ISSUE TITLE
Bug: Non-matching, double-character truthy

### ISSUE THREAD

**Issue by jaketrimble** [3chospirits/badwords-filter#4]
```
const config = {
  list: ['cok']
};
const filter = new Filter(config);

filter.isUnclean('cook'); // true, expected false
```

**Comment by 3chospirits** [comment]
Hey, this is not actually a bug, but expected behavior. The intention of this package is to have heightened detection so that words with extra duplicate letters will still be detected. This is to prevent people from being able to bypass word filters by merely adding duplicate letters within the word. 
it is expected that a list containing 'abc' will be triggered on all of the following
- abc
- aabc
- abbc
- abcc
- aabbcc
- aaaaaaabbbbbbbbccccc
etc.
